config/routes.rb
Rails.application.routes.draw do
  
  get 'billboard/index'
  resources :stores
  resources :collections
  resources :advertisements 
  resources :users, only: [:new, :create]
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root 'billboard#index'
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
   validates :title, :store_id, :product_url, :description, :image_url, :collection_id, :effective_date, :expiration_date, presence: true
   
   validate :effective_date_cannot_be_in_the_past
   validate :expiration_date_cannot_be_before_effective_date
   validate :expiration_date_cannot_be_today

   belongs_to :collection
   belongs_to :store

   MAX_ADS_PER_STORE = 3

   def self.max_ads_reached?(store_id:)
      Advertisement.where(store_id: store_id).count >= MAX_ADS_PER_STORE 
   end

   def self.remove_expired_ads
      Advertisement.destroy_by('expiration_date <= ?', Date.today)
   end

   def effective_date_cannot_be_in_the_past
      if effective_date.present? && effective_date < Date.today
        errors.add(:effective_date, "can't be in the past")
      end
   end    

    def expiration_date_cannot_be_before_effective_date
      if expiration_date.present? && expiration_date <= effective_date
        errors.add(:expiration_date, "can't be before the effective date or the same day")
      end
   end 

   def expiration_date_cannot_be_today
      if expiration_date.present? && expiration_date == Date.today
        errors.add(:expiration_date, "can't be today")
      end
   end 
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]
  #before_action :count_ads, only: [:create]
 

  # GET /advertisements
  # GET /advertisements.json
  def index
    
      # @advertisements = Advertisement.all
      @store = Store.find_by('user_id = ?', current_user.id)
      @advertisements = Advertisement.where('store_id = ?', @store.id)
    
      
    
    # @advertisements = Advertisement.all unless defined? @store_id
  end

  # GET /advertisements/1
  # GET /advertisements/1.json
  def show
  end

  # GET /advertisements/new
  def new
    @advertisement = Advertisement.new
    @store = Store.find_by('user_id = ?', current_user.id)
    store_id = @store.id
    # Each store are not allowed to add more than 3 active(not expired) ads.
    if Advertisement.max_ads_reached?(store_id: store_id)
      redirect_to advertisements_url, notice: 'The store has already reached the maximum number of ads.'
    end
  end

  # GET /advertisements/1/edit
  def edit
    @store = Store.find_by('user_id = ?', current_user.id)
  end

  # POST /advertisements
  # POST /advertisements.json
  def create
    
    store_id = advertisement_params[:store_id]

    # @advertisements = Advertisement.where("store_id = ?", store_id)
    # count = @advertisements.count
    # @count = search_store(store_id)
    # count = @advertisements.count
    
      respond_to do |format|
        # binding.pry
        # if Advertisement.max_ads_reached?(store_id: store_id)
          # @store_id = advertisement_params[:store_id]
          # @advertisements2 = Advertisement.where("store_id = ?", @store_id)
          # format.html { redirect_to search_store_advertisements_url(store_id: store_id), notice: 'The store has already reached the maximum number of ads.' }
          # format.html { redirect_to billboard_index_url, notice: 'The store has already reached the maximum number of ads'}
          # format.json { head :no_content }
          # return
        # else
          @advertisement = Advertisement.new(advertisement_params)
          if !@advertisement.valid?
            format.html { render 'new'}
            # format.html { redirect_to @advertisement, notice: @advertisement.errors.messages }
          else
            if @advertisement.save
              format.html { redirect_to @advertisement, notice: 'Advertisement was successfully created.'}
              format.json { render :show, status: :created, location: @advertisement }
            else
              format.html { render :new }
              format.json { render json: @advertisement.errors, status: :unprocessable_entity }
            end
          end
        # end
      end
    end

  # PATCH/PUT /advertisements/1
  # PATCH/PUT /advertisements/1.json
  def update
    respond_to do |format|
      if @advertisement.update(advertisement_params)
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertisement }
      else
        format.html { render :edit }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisements/1
  # DELETE /advertisements/1.json
  def destroy
    @advertisement.destroy
    respond_to do |format|
      format.html { redirect_to advertisements_url, notice: 'Advertisement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def search_store
    # @advertisements = Advertisement.where("store_id = ?", params[:store_id])
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisement
      @advertisement = Advertisement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisement_params
      params.require(:advertisement).permit(:title, :store_id, :product_url, :description, :image_url, :collection_id, :effective_date, :expiration_date, :active)
    end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/views/advertisements/_form.html.erb
<%= form_with(model: advertisement, local: true) do |form| %>
  <% if advertisement.errors.any? %>
    <div id="error_explanation" class="text-danger">
      <h2><%= pluralize(advertisement.errors.count, "error") %> prohibited this advertisement from being saved:</h2>
      <ul>
        <% advertisement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :product_url %>
    <%= form.text_field :product_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image_url, 'Image' %>
    <%= form.text_field :image_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :effective_date %>
    <%= form.text_field :effective_date, data:{ provide: 'datepicker',  date_format: 'yyyy-mm-dd'}, class: 'form-control', value: "#{form.object.effective_date.strftime("%Y-%m-%d") unless form.object.new_record?}" %>
  </div>

  <div class="form-group">
    <%= form.label :expiration_date %>
    <%= form.text_field :expiration_date, data:{ provide: 'datepicker',  date_format: 'yyyy-mm-dd'}, class: 'form-control', value: "#{form.object.expiration_date.strftime("%Y-%m-%d") unless form.object.new_record?}" %>
  </div>

  <div class="form-group">
    <%= form.label :collection_title%><br>
    <%= form.collection_select(:collection_id, Collection.all, :id, :title, { class: 'form-control'}) %>
  </div>

  <% if @store.nil? %>
    <%= form.hidden_field :store_id, value: "#{@advertisement.store_id}" %>
  <% else %>
    <%= form.hidden_field :store_id, value: @store.id %>
  <% end %>

  <div>
    <%= form.submit :submit, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/advertisements/edit.html.erb
  <div class="row">
    <div class="col-sm-10 offset-sm-1">
      <h1 class="display-5">Editing Advertisement</h1>
      <%= render 'form', advertisement: @advertisement %>
    </div>
  </div>

app/views/advertisements/index.html.erb
<p id="notice" class="text-danger"><%= notice %></p>

<h1 class="text-center mb-5">Advertisements</h1>
<div class="row justify-content-center">
  <div class="col-auto">
    <table class="table table-responsive text-center">
      <thead class="thead-light">
        <tr>
          <th scope="col">Image</th>
          <th scope="col">Title</th>
          <th scope="col">Description</th>
          <th scope="col">Effective</th>
          <th scope="col">Expiration</th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @advertisements.each do |advertisement| %>
          <tr>
            <td><%= image_tag(advertisement.image_url, size: '160x100', alt: 'Ad Image', class: 'img-fluid')%></td>
            <td><%= advertisement.title %></td>
            <% @store = Store.find(advertisement.store_id)%>
            <td><%= advertisement.description %></td>
            <td><%= advertisement.effective_date.strftime('%Y-%m-%d') %></td>
            <td><%= advertisement.expiration_date.strftime('%Y-%m-%d') %></td>
            <td><%= link_to 'More...', advertisement, class: 'btn btn-success' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/advertisements/new.html.erb
  <div class="row">
    <div class="col-sm-10 offset-sm-1">
      <h1 class="display-5">New Advertisement</h1>
      <%= render 'form', advertisement: @advertisement %>
    </div>
  </div>

app/views/advertisements/search_store.html.erb
<p id="notice" class="text-danger"><%= notice %></p>

<h1 class="text-center">Store Advertisements</h1>

<!--<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown button
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>-->

<!--<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <%= link_to 'logo', billboard_index_path, :class => 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        
        <%= link_to 'Home', billboard_index_path, :class => 'nav-link' %>
      </li>
      <li class="nav-item">
        
        <%= link_to 'New Advertisement', new_advertisement_path, :class => 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>-->


<table class="table table-responsive text-center">
  <thead class="thead-light">
    <tr>
      <th scope="col">Image</th>
      <th scope="col">Title</th>
      <!--<th scope="col">Store</th>-->
      <th scope="col">Description</th>
      <th scope="col">Effective</th>
      <th scope="col">Expiration</th>
      <!--<th scope="col">Collection</th>-->
      <th scope="col" colspan="3"></th>
      
    </tr>
  </thead>

  <tbody>
    <% @advertisements.each do |advertisement| %>
      <tr>
        <td><%= image_tag(advertisement.image_url, size: "160x100", alt: "Ad Image")%></td>
        <td><%= advertisement.title %></td>
        <!--<% @store = Store.find(advertisement.store_id)%>
        <td><%= @store.title %></td>-->
        <!--<td><a class="alert-link" href="<%= advertisement.product_url %>" target="_blank">SHOP NOW</a></td>-->
        <td><%= advertisement.description %></td>
        <td><%= advertisement.effective_date.strftime('%Y-%m-%d') %></td>
        <td><%= advertisement.expiration_date.strftime('%Y-%m-%d') %></td>
        <!--<% @collection = Collection.find(advertisement.collection_id)%>
        <td><%= @collection.title %></td>-->
        
        <td><%= link_to 'More...', advertisement, class: 'btn btn-success' %></td>
       <!--<td><%= link_to 'Edit', edit_advertisement_path(advertisement), :class => 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', advertisement, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/advertisements/show.html.erb
<p id="notice" class="text-danger"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @advertisement.title %>
</p>

<p>
  <strong>Store:</strong>
  <% id = @advertisement.store_id%>
  <% @store = Store.find(id)%>
  <%= @store.title %>
</p>

<p>
  <strong>Product url:</strong>
  <%= @advertisement.product_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @advertisement.description %>
</p>

<p>
  <strong>Effective Date:</strong>
  <%= @advertisement.effective_date.strftime('%Y-%m-%d') %>     
</p>

<p>
  <strong>Exiration Date:</strong>
  <%= @advertisement.expiration_date.strftime('%Y-%m-%d') %>
</p>

<p>
  <strong>Image:</strong>
  <%= @advertisement.image_url %>
</p>

<p>
  <strong>Collection:</strong>
  <% id = @advertisement.collection_id%>
  <% @collection = Collection.find(id)%>
  <%= @collection.title %>
</p>

<%= link_to 'Edit', edit_advertisement_path(@advertisement), class: 'btn btn-warning' %>
<%= link_to 'Destroy', @advertisement, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>