config/routes.rb
Rails.application.routes.draw do
  
  get 'billboard/index'
  resources :stores
  resources :collections
  resources :advertisements 
  resources :users, only: [:new, :create]
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root 'billboard#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrepo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
        <%= link_to 'LOGO', billboard_index_url, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'Home', billboard_index_url, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <% if current_page?(billboard_index_url) || current_page?(root_url) %>
                <% if !logged_in? %>
                  <%= link_to 'Login', login_url, class: 'nav-link' %>
                <% else %>
                    <%= link_to 'Advertisements', advertisements_url, class: 'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'Logout', logout_url, method: :delete, class: 'nav-link' %>
                <% end %>
              <% elsif current_page?(advertisements_url) %>
                <%= link_to 'New Advertisement', new_advertisement_url, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Logout', logout_url, method: :delete, class: 'nav-link' %>
              <% elsif !current_page?(login_url) && !current_page?(signup_url) %>
                  <%= link_to 'Advertisements', advertisements_url, class: 'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'Logout', logout_url, method: :delete, class: 'nav-link' %>
              <% end %>
            </li>
            <% if logged_in? %>
              <li class="nav-item"><span class="nav-link text-success"><%= current_user.username %></span></li>
            <% end %>
          </ul>
          <% if current_page?(billboard_index_url) || current_page?(root_url)%>
            <%= form_with(url: billboard_index_url, method: "get", class: 'form-inline my-2 my-lg-0', local: true) do |form| %>
              <%= form.collection_select(:collection_id, Collection.all, :id, :title, { prompt: 'All Collections' }, class: 'form-control mr-sm-2' ) %>
              <%= form.submit "search", class: 'btn btn-outline-success my-2 my-sm-0' %>
            <% end %>
          <% end %>
        </div>
      </nav>
    </header>
    <div class="container" id="main">
      <%= yield %>
    </div>
  </body>
</html>